version: "3.8"

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/conf.d/:/etc/nginx/conf.d
      - /home/ubuntu/etc/ssl:/etc/ssl
    ports:
      - 80:80
      - 443:443
    networks:
      - ondo
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend/ondo
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - ${BACKEND_PORT}:8080
    environment:
      - SPRING_PROFILES_ACTIVE=oauth
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - ondo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - ${FRONTEND_PORT}:3000
    networks:
      - ondo

networks:
  ondo:
    external: true
